// <auto-generated />
using System;
using InteractiveBookingBackend.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InteractiveBookingBackend.Data.Migrations
{
    [DbContext(typeof(InteractiveBookingContext))]
    partial class InteractiveBookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InteractiveBookingBackend.Model.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Booking", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("694ac33a-9727-497a-a578-23a48aa9b118"),
                            EndDate = new DateTime(2024, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1000,
                            StartDate = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = new Guid("029c1d53-21ae-4169-9e69-d0f19751a89f")
                        },
                        new
                        {
                            Id = new Guid("d64e4ae4-2b44-4de0-b654-312193ff2a02"),
                            EndDate = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 2000,
                            StartDate = new DateTime(2024, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = new Guid("8f4a212c-8cf1-4806-9937-6c41bb8ae2ae")
                        },
                        new
                        {
                            Id = new Guid("58056c04-2e55-41c7-85e9-d62da7c67698"),
                            EndDate = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1000,
                            StartDate = new DateTime(2024, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = new Guid("4360ec35-ef9f-4d3c-863c-b062d5fa0dba")
                        },
                        new
                        {
                            Id = new Guid("2dcc976c-4cdb-4f9b-afa9-c90607ddd114"),
                            EndDate = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1000,
                            StartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = new Guid("ffa51ac1-dff4-4827-a3d8-2693e10b7392")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
